version: '3'

services:
  hiddify:
    image: hiddify
    build: .
    ports:
      - 443:443
      - 80:80
    # privileged: true
    # cap_add:
    #   - NET_ADMIN
    volumes:
       - ./hiddify-panel/hiddifypanel.db:/opt/hiddify-manager/hiddify-panel/hiddifypanel.db
       - ./ssl/:/opt/hiddify-manager/ssl/
